### ISSUE TITLE
Communications Refresh button is not needed

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#48]
Steps to reproduce:

1. While logged into HB, without having the patient record opened, received a message from the patient;
2. Get into the Dashboard/Communications and see if you need to need to click on the *Refresh* button to view changes;

Actual result:

2. No, you do not.

Expected result:

2. Since that button is not useful in Communications, why not remove it?

**Comment by tudorsss** [comment]
Hey @unleu,

"Nothing happens on selecting the button". You need to create a new allergy or medications then click on the refresh button; it will then refresh the table and present to you the new data.

If you didn't create a new allergy or medications (I'm talking now about the needs review example) then the refresh button won't refresh the table list because it doesn't have to.

So this is not a bug, do you agree?

**Comment by unleu** [comment]
@tudorsss the thing is the refresh button on needs review is working even if there is no new allergy or medication. On communications, the refresh button does nothing on press, but still, the messages are displayed here because of auto refresh ( i think )

I posted the bug because refresh button in communications is acting differently than the other refresh buttons.

**Comment by tudorsss** [comment]
OK, I updated your bug, please add it.

**Comment by unleu** [comment]
added
