### ISSUE TITLE
SC - "Review By" field is populated with the user's ID, not the user's display name

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#63]
Precondition: Make sure the patient has reviewed **Allergies** and reviewed **Nurse visitation forms**

1. Login to SC and open a patient's record;
2. Go to **Allergies**  or to "Nurse visitation forms" and check **Reviewed by** column;

Actual result:

2 A number is displayed there instead of the users Display name. Probably the users ID.

Expected result:

2 The users Display name should be shown there.

![screen shot 2016-06-29 at 17 09 21](https://cloud.githubusercontent.com/assets/12154831/16455259/52e187c0-3e1c-11e6-8d99-a7713ad13ef4.png)

**Comment by tudorsss** [comment]
Hey @unleu,

Please check and see if other review columns have the same issue; if that's the case, we need to update the bug; if that's not the case, we need to mention this in the bug also.

Here's the updated version:

Precondition: Make sure the patient has reviewed allergies 

1. Login to SC and open a patient's record;
2. Go to **Allergies** and check the patient's **Reviewed by** column;

Actual result:

2 . A number is displayed there instead of the users Display name. Probably the user's ID.

Expected result:

2 The user's Display name should be shown here.

![screen shot 2016-06-29 at 17 09 21](https://cloud.githubusercontent.com/assets/12154831/16455259/52e187c0-3e1c-11e6-8d99-a7713ad13ef4.png)

**Comment by unleu** [comment]
https://envoy.myjetbrains.com/youtrack/issue/SC-132
